from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import List, Optional
from fpdf import FPDF
import io
import datetime

router = APIRouter()


class PersonDetails(BaseModel):
    name: str = ""
    fatherName: str = ""
    address: str = ""
    phone: str = ""
    aadhaar: str = ""


class PropertyDetails(BaseModel):
    address: str = ""
    city: str = ""
    state: str = "Maharashtra"
    pincode: str = ""
    type: str = "Residential"


class TermsDetails(BaseModel):
    rent: str = ""
    deposit: str = ""
    startDate: str = ""
    duration: int = 11
    escalation: float = 5
    clauses: List[str] = []


class AgreementRequest(BaseModel):
    landlord: PersonDetails
    tenant: PersonDetails
    property: PropertyDetails
    terms: TermsDetails
    amountInWords: str = ""
    depositInWords: str = ""


class AgreementPDF(FPDF):
    def header(self):
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(180, 180, 180)
        self.cell(0, 10, "Generated by ToolsWaala.in | Free Rent Agreement Generator", align="C")


def format_date_long(date_str):
    try:
        d = datetime.datetime.strptime(date_str, "%Y-%m-%d")
        return d.strftime("%d %B %Y")
    except Exception:
        return date_str


def get_end_date(start_str, months):
    try:
        d = datetime.datetime.strptime(start_str, "%Y-%m-%d")
        end = d + datetime.timedelta(days=months * 30)
        return end.strftime("%d %B %Y")
    except Exception:
        return ""


@router.post("/agreement/generate")
async def generate_agreement(data: AgreementRequest):
    pdf = AgreementPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=25)

    start_formatted = format_date_long(data.terms.startDate)
    end_formatted = get_end_date(data.terms.startDate, data.terms.duration)
    rent = data.terms.rent or "0"
    deposit = data.terms.deposit or "0"

    # --- Title ---
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(13, 27, 42)
    pdf.cell(0, 12, "RENT AGREEMENT", ln=True, align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, f"(Leave and License Agreement)", ln=True, align="C")
    pdf.ln(8)

    # --- Preamble ---
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(40, 40, 40)

    preamble = (
        f"This Rent Agreement (\"Agreement\") is made and executed on this "
        f"{start_formatted} at {data.property.city}, {data.property.state}."
    )
    pdf.multi_cell(0, 6, preamble)
    pdf.ln(4)

    # --- Between ---
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "BETWEEN:", ln=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    landlord_text = (
        f"LANDLORD/LICENSOR: {data.landlord.name}, "
        f"S/o / D/o {data.landlord.fatherName or 'N/A'}, "
        f"residing at {data.landlord.address or 'N/A'}, "
        f"Phone: {data.landlord.phone or 'N/A'}"
    )
    if data.landlord.aadhaar:
        landlord_text += f", Aadhaar: {data.landlord.aadhaar}"
    landlord_text += " (hereinafter referred to as the \"LANDLORD\", which expression shall include his/her heirs, successors, and assigns)."
    pdf.multi_cell(0, 6, landlord_text)
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "AND", ln=True, align="C")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    tenant_text = (
        f"TENANT/LICENSEE: {data.tenant.name}, "
        f"S/o / D/o {data.tenant.fatherName or 'N/A'}, "
        f"residing at {data.tenant.address or 'N/A'}, "
        f"Phone: {data.tenant.phone or 'N/A'}"
    )
    if data.tenant.aadhaar:
        tenant_text += f", Aadhaar: {data.tenant.aadhaar}"
    tenant_text += " (hereinafter referred to as the \"TENANT\", which expression shall include his/her heirs, successors, and assigns)."
    pdf.multi_cell(0, 6, tenant_text)
    pdf.ln(5)

    # --- Property ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(255, 107, 0)
    pdf.cell(0, 7, "SCHEDULE OF PROPERTY", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(40, 40, 40)
    property_text = (
        f"The {data.property.type.lower()} property situated at: "
        f"{data.property.address}, {data.property.city}, "
        f"{data.property.state} - {data.property.pincode}."
    )
    pdf.multi_cell(0, 6, property_text)
    pdf.ln(5)

    # --- Terms ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(255, 107, 0)
    pdf.cell(0, 7, "TERMS AND CONDITIONS", ln=True)
    pdf.set_text_color(40, 40, 40)
    pdf.ln(2)

    # Key terms
    key_terms = [
        f"Period of Agreement: {data.terms.duration} months, commencing from {start_formatted} to {end_formatted}.",
        f"Monthly Rent: Rs. {rent}/- ({data.amountInWords or 'N/A'}) payable on or before the 5th of each month.",
        f"Security Deposit: Rs. {deposit}/- ({data.depositInWords or 'N/A'}) paid by the Tenant to the Landlord, refundable at the time of vacating after deducting any dues.",
        f"Annual Rent Escalation: The rent shall be increased by {data.terms.escalation}% per annum after the completion of the agreement period, if renewed.",
        f"Purpose: The premises shall be used solely for {data.property.type.lower()} purposes.",
    ]

    pdf.set_font("Helvetica", "", 10)
    for i, term in enumerate(key_terms, 1):
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(8, 6, f"{i}.")
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 6, term)
        pdf.ln(2)

    # Additional clauses
    if data.terms.clauses:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(255, 107, 0)
        pdf.cell(0, 7, "ADDITIONAL CLAUSES", ln=True)
        pdf.set_text_color(40, 40, 40)
        pdf.ln(2)

        pdf.set_font("Helvetica", "", 10)
        for i, clause in enumerate(data.terms.clauses, len(key_terms) + 1):
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(8, 6, f"{i}.")
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 6, clause)
            pdf.ln(1)

    # --- Jurisdiction ---
    pdf.ln(5)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "JURISDICTION:", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(
        0, 6,
        f"Any dispute arising out of this agreement shall be subject to the exclusive "
        f"jurisdiction of the courts at {data.property.city}, {data.property.state}."
    )

    # --- Witness ---
    pdf.ln(5)
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(
        0, 6,
        "IN WITNESS WHEREOF, the Landlord and Tenant have set their hands on this agreement "
        f"on the day and year first above written at {data.property.city}."
    )

    # --- Signatures ---
    pdf.ln(20)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(95, 6, "LANDLORD", align="L")
    pdf.cell(95, 6, "TENANT", align="R", ln=True)
    pdf.ln(15)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(95, 5, "_________________________", align="L")
    pdf.cell(95, 5, "_________________________", align="R", ln=True)
    pdf.cell(95, 5, f"({data.landlord.name})", align="L")
    pdf.cell(95, 5, f"({data.tenant.name})", align="R", ln=True)

    pdf.ln(15)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 6, "WITNESSES:", ln=True)
    pdf.ln(10)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(95, 5, "1. _________________________", align="L")
    pdf.cell(95, 5, "2. _________________________", align="L", ln=True)
    pdf.cell(95, 5, "   Name:", align="L")
    pdf.cell(95, 5, "   Name:", align="L", ln=True)
    pdf.cell(95, 5, "   Address:", align="L")
    pdf.cell(95, 5, "   Address:", align="L", ln=True)

    # Output
    buf = io.BytesIO()
    try:
        pdf.output(buf)
    except UnicodeEncodeError:
        from fastapi import HTTPException
        raise HTTPException(status_code=400, detail="Special characters and non-English text (like Hindi) are currently not supported in PDFs. Please use standard English text.")
    except Exception as e:
        from fastapi import HTTPException
        raise HTTPException(status_code=500, detail=f"PDF Generation failed: {str(e)}")

    buf.seek(0)

    return StreamingResponse(
        buf,
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=rent-agreement.pdf"},
    )
