from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import List, Optional
from fpdf import FPDF
import io
import datetime

router = APIRouter()


class LineItem(BaseModel):
    description: str = ""
    qty: float = 0
    rate: float = 0
    gstRate: float = 0
    taxableAmount: float = 0
    cgst: float = 0
    sgst: float = 0
    igst: float = 0
    total: float = 0


class Totals(BaseModel):
    taxable: float = 0
    cgst: float = 0
    sgst: float = 0
    igst: float = 0
    total: float = 0


class PartyDetails(BaseModel):
    name: str = ""
    address: str = ""
    gstin: str = ""
    phone: str = ""
    email: str = ""
    state: str = ""


class InvoiceDetails(BaseModel):
    number: str = ""
    date: str = ""
    dueDate: str = ""
    notes: str = ""


class InvoiceRequest(BaseModel):
    seller: PartyDetails
    buyer: PartyDetails
    invoice: InvoiceDetails
    items: List[LineItem]
    totals: Totals
    isSameState: bool = True
    amountInWords: str = ""


class InvoicePDF(FPDF):
    def header(self):
        pass

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(180, 180, 180)
        self.cell(0, 10, "Generated by ToolsWaala.in | Free GST Invoice Generator", align="C")


@router.post("/invoice/generate")
async def generate_invoice(data: InvoiceRequest):
    pdf = InvoicePDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # --- Title ---
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(255, 107, 0)
    pdf.cell(0, 12, "TAX INVOICE", ln=True, align="R")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, f"Invoice #: {data.invoice.number}", ln=True, align="R")
    pdf.cell(0, 5, f"Date: {data.invoice.date}", ln=True, align="R")
    pdf.ln(5)

    # --- Seller ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(13, 27, 42)
    pdf.cell(0, 7, data.seller.name, ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    if data.seller.address:
        pdf.cell(0, 5, data.seller.address, ln=True)
    if data.seller.gstin:
        pdf.cell(0, 5, f"GSTIN: {data.seller.gstin}", ln=True)
    if data.seller.phone:
        pdf.cell(0, 5, f"Phone: {data.seller.phone}", ln=True)
    if data.seller.state:
        pdf.cell(0, 5, f"State: {data.seller.state}", ln=True)
    pdf.ln(5)

    # --- Buyer ---
    pdf.set_fill_color(248, 249, 250)
    pdf.rect(10, pdf.get_y(), 190, 28, "F")
    y_start = pdf.get_y()
    pdf.set_xy(12, y_start + 2)
    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 4, "BILL TO", ln=True)
    pdf.set_x(12)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(13, 27, 42)
    pdf.cell(0, 6, data.buyer.name, ln=True)
    pdf.set_x(12)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    if data.buyer.address:
        pdf.cell(0, 5, data.buyer.address, ln=True)
        pdf.set_x(12)
    if data.buyer.gstin:
        pdf.cell(0, 5, f"GSTIN: {data.buyer.gstin}", ln=True)
    pdf.set_y(y_start + 30)
    pdf.ln(3)

    # --- Table Header ---
    col_widths = [10, 60, 15, 25, 15, 25, 20, 20]
    headers = ["#", "Description", "Qty", "Rate", "GST%", "Tax", "Amount"]
    # Adjust widths for same-state vs inter-state
    if data.isSameState:
        col_widths = [8, 50, 12, 22, 12, 22, 22, 22, 20]
        headers = ["#", "Description", "Qty", "Rate", "GST%", "CGST", "SGST", "Amount"]
    else:
        col_widths = [8, 55, 12, 25, 12, 25, 25, 28]
        headers = ["#", "Description", "Qty", "Rate", "GST%", "IGST", "Amount"]

    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(13, 27, 42)
    pdf.set_text_color(255, 255, 255)

    for i, h in enumerate(headers):
        w = col_widths[i] if i < len(col_widths) else 20
        pdf.cell(w, 8, h, border=0, fill=True, align="C" if i > 1 else "L")
    pdf.ln()

    # --- Table Rows ---
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(60, 60, 60)

    for idx, item in enumerate(data.items):
        pdf.set_fill_color(255, 255, 255) if idx % 2 == 0 else pdf.set_fill_color(252, 252, 252)
        fill = idx % 2 != 0

        if data.isSameState:
            cells = [
                str(idx + 1),
                item.description[:30] or "-",
                str(int(item.qty)),
                f"Rs.{item.rate:,.2f}",
                f"{item.gstRate}%",
                f"Rs.{item.cgst:,.2f}",
                f"Rs.{item.sgst:,.2f}",
                f"Rs.{item.total:,.2f}",
            ]
        else:
            cells = [
                str(idx + 1),
                item.description[:35] or "-",
                str(int(item.qty)),
                f"Rs.{item.rate:,.2f}",
                f"{item.gstRate}%",
                f"Rs.{item.igst:,.2f}",
                f"Rs.{item.total:,.2f}",
            ]

        for i, c in enumerate(cells):
            w = col_widths[i] if i < len(col_widths) else 20
            pdf.cell(w, 7, c, border=0, fill=fill, align="R" if i > 1 else "L")
        pdf.ln()

    pdf.ln(3)

    # --- Totals ---
    x_label = 120
    x_val = 170
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.set_x(x_label)
    pdf.cell(50, 6, "Taxable Amount:", align="R")
    pdf.cell(30, 6, f"Rs.{data.totals.taxable:,.2f}", align="R", ln=True)

    if data.isSameState:
        pdf.set_x(x_label)
        pdf.cell(50, 6, "CGST:", align="R")
        pdf.cell(30, 6, f"Rs.{data.totals.cgst:,.2f}", align="R", ln=True)
        pdf.set_x(x_label)
        pdf.cell(50, 6, "SGST:", align="R")
        pdf.cell(30, 6, f"Rs.{data.totals.sgst:,.2f}", align="R", ln=True)
    else:
        pdf.set_x(x_label)
        pdf.cell(50, 6, "IGST:", align="R")
        pdf.cell(30, 6, f"Rs.{data.totals.igst:,.2f}", align="R", ln=True)

    pdf.ln(2)
    pdf.set_draw_color(255, 107, 0)
    pdf.line(x_label, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(255, 107, 0)
    pdf.set_x(x_label)
    pdf.cell(50, 8, "TOTAL:", align="R")
    pdf.cell(30, 8, f"Rs.{data.totals.total:,.2f}", align="R", ln=True)

    # Amount in Words
    if data.amountInWords:
        pdf.ln(3)
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(120, 120, 120)
        pdf.cell(0, 5, f"Amount in words: {data.amountInWords}", ln=True)

    # Notes
    if data.invoice.notes:
        pdf.ln(5)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 5, f"Notes: {data.invoice.notes}", ln=True)

    # Signature
    pdf.ln(15)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(13, 27, 42)
    pdf.cell(95, 5, "", align="L")
    pdf.cell(95, 5, "Authorized Signatory", align="R", ln=True)
    pdf.cell(95, 5, "", align="L")
    pdf.cell(95, 5, data.seller.name, align="R", ln=True)

    # Output
    buf = io.BytesIO()
    try:
        pdf.output(buf)
    except UnicodeEncodeError:
        from fastapi import HTTPException
        raise HTTPException(status_code=400, detail="Special characters and non-English text (like Hindi) are currently not supported in PDFs. Please use standard English text.")
    except Exception as e:
        from fastapi import HTTPException
        raise HTTPException(status_code=500, detail=f"PDF Generation failed: {str(e)}")

    buf.seek(0)

    return StreamingResponse(
        buf,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={data.invoice.number}.pdf"},
    )
