from fastapi import APIRouter
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import Optional
from fpdf import FPDF
import io

router = APIRouter()


class CompanyDetails(BaseModel):
    name: str = ""
    address: str = ""


class EmployeeDetails(BaseModel):
    name: str = ""
    empId: str = ""
    designation: str = ""
    department: str = ""
    pan: str = ""
    bankAccount: str = ""
    bankName: str = ""


class PeriodDetails(BaseModel):
    month: str = ""
    year: int = 2026


class EarningsDetails(BaseModel):
    basic: float = 0
    hra: float = 0
    conveyance: float = 0
    medical: float = 0
    special: float = 0
    otherAllowance: float = 0
    total: float = 0


class DeductionsDetails(BaseModel):
    pf: float = 0
    professionalTax: float = 0
    tds: float = 0
    otherDeduction: float = 0
    total: float = 0


class SalaryRequest(BaseModel):
    company: CompanyDetails
    employee: EmployeeDetails
    period: PeriodDetails
    earnings: EarningsDetails
    deductions: DeductionsDetails
    netPay: float = 0


class SalaryPDF(FPDF):
    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(180, 180, 180)
        self.cell(0, 10, "Generated by ToolsWaala.in | Free Salary Slip Generator", align="C")


def fmt(amount):
    return f"Rs. {amount:,.2f}"


@router.post("/salary/generate")
async def generate_salary(data: SalaryRequest):
    pdf = SalaryPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # --- Header / Company ---
    pdf.set_fill_color(13, 27, 42)
    pdf.rect(10, 10, 190, 25, "F")

    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(15, 14)
    pdf.cell(0, 8, data.company.name or "Company Name", ln=True)
    pdf.set_x(15)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(200, 200, 200)
    pdf.cell(0, 5, data.company.address or "", ln=True)

    pdf.set_xy(10, 38)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(255, 107, 0)
    pdf.cell(0, 8, f"PAYSLIP FOR {data.period.month.upper()} {data.period.year}", ln=True, align="C")
    pdf.ln(3)

    # --- Employee Info ---
    pdf.set_fill_color(248, 249, 250)
    y_start = pdf.get_y()
    pdf.rect(10, y_start, 190, 30, "F")

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)

    # Left column
    info_left = [
        ("Employee Name", data.employee.name),
        ("Employee ID", data.employee.empId),
        ("Designation", data.employee.designation),
    ]
    # Right column
    info_right = [
        ("Department", data.employee.department),
        ("PAN", data.employee.pan),
        ("Bank A/c", data.employee.bankAccount),
    ]

    for i, (label, value) in enumerate(info_left):
        pdf.set_xy(15, y_start + 3 + i * 8)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(130, 130, 130)
        pdf.cell(30, 5, label)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(13, 27, 42)
        pdf.cell(60, 5, value or "N/A")

    for i, (label, value) in enumerate(info_right):
        pdf.set_xy(110, y_start + 3 + i * 8)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(130, 130, 130)
        pdf.cell(30, 5, label)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(13, 27, 42)
        pdf.cell(60, 5, value or "N/A")

    pdf.set_y(y_start + 34)
    pdf.ln(3)

    # --- Earnings & Deductions Table ---
    col_w = 95

    # Table headers
    pdf.set_fill_color(13, 27, 42)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(col_w, 8, "  EARNINGS", fill=True)
    pdf.cell(col_w, 8, "  DEDUCTIONS", fill=True, ln=True)

    # Table body
    earnings_rows = [
        ("Basic Salary", data.earnings.basic),
        ("HRA", data.earnings.hra),
        ("Conveyance Allowance", data.earnings.conveyance),
        ("Medical Allowance", data.earnings.medical),
        ("Special Allowance", data.earnings.special),
        ("Other Allowance", data.earnings.otherAllowance),
    ]

    deductions_rows = [
        ("Provident Fund (PF)", data.deductions.pf),
        ("Professional Tax", data.deductions.professionalTax),
        ("TDS / Income Tax", data.deductions.tds),
        ("Other Deductions", data.deductions.otherDeduction),
        ("", 0),
        ("", 0),
    ]

    pdf.set_text_color(60, 60, 60)
    for i in range(len(earnings_rows)):
        e_label, e_val = earnings_rows[i]
        d_label, d_val = deductions_rows[i]

        bg = i % 2 != 0
        if bg:
            pdf.set_fill_color(252, 252, 252)
        else:
            pdf.set_fill_color(255, 255, 255)

        # Earnings
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(55, 7, f"  {e_label}", fill=bg)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(40, 7, fmt(e_val) if e_val else "", align="R", fill=bg)

        # Deductions
        pdf.set_font("Helvetica", "", 9)
        pdf.cell(55, 7, f"  {d_label}", fill=bg)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(40, 7, fmt(d_val) if d_val else "", align="R", fill=bg, ln=True)

    # --- Totals Row ---
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())

    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(13, 27, 42)
    pdf.cell(55, 8, "  Total Earnings", fill=True)
    pdf.set_text_color(22, 163, 74)
    pdf.cell(40, 8, fmt(data.earnings.total), align="R", fill=True)
    pdf.set_text_color(13, 27, 42)
    pdf.cell(55, 8, "  Total Deductions", fill=True)
    pdf.set_text_color(220, 38, 38)
    pdf.cell(40, 8, fmt(data.deductions.total), align="R", fill=True, ln=True)

    pdf.ln(5)

    # --- Net Pay ---
    pdf.set_fill_color(255, 107, 0)
    pdf.rect(10, pdf.get_y(), 190, 18, "F")
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(255, 255, 255)
    y_net = pdf.get_y()
    pdf.set_xy(15, y_net + 3)
    pdf.cell(90, 12, "NET PAY")
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(90, 12, fmt(data.netPay), align="R")
    pdf.ln()

    pdf.set_y(y_net + 22)
    pdf.ln(5)

    # --- Footer notes ---
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.multi_cell(0, 5, "This is a computer-generated salary slip and does not require a signature. For any queries, contact the HR department.")

    # --- Signature ---
    pdf.ln(20)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(13, 27, 42)
    pdf.cell(95, 5, "", align="L")
    pdf.cell(95, 5, "Authorized Signatory", align="R", ln=True)
    pdf.cell(95, 5, "", align="L")
    pdf.cell(95, 5, data.company.name, align="R", ln=True)

    # Output
    buf = io.BytesIO()
    try:
        pdf.output(buf)
    except UnicodeEncodeError:
        from fastapi import HTTPException
        raise HTTPException(status_code=400, detail="Special characters and non-English text (like Hindi) are currently not supported in PDFs. Please use standard English text.")
    except Exception as e:
        from fastapi import HTTPException
        raise HTTPException(status_code=500, detail=f"PDF Generation failed: {str(e)}")

    buf.seek(0)

    filename = f"salary-slip-{data.period.month}-{data.period.year}.pdf"
    return StreamingResponse(
        buf,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )
